import { clamp } from "../utils/helpers.js";
import { isValidTime } from "../utils/time.js";

export const SAMPLE_EVENTS = [
  {
    id: "evt-1",
    name: "Design Jam",
    category: "Design",
    cost: 18,
    impact: 52,
    priority: 3,
    staffRequired: 4,
    equipmentRequired: 3,
    start: "09:00",
    end: "10:30",
    note: "Studio-style sprint for campus creatives.",
  },
  {
    id: "evt-2",
    name: "Robotics Arena",
    category: "Tech",
    cost: 24,
    impact: 68,
    priority: 5,
    staffRequired: 8,
    equipmentRequired: 7,
    start: "10:15",
    end: "12:00",
    note: "High-energy robot battle with faculty judges.",
  },
  {
    id: "evt-3",
    name: "Food Street",
    category: "Food",
    cost: 14,
    impact: 30,
    priority: 2,
    staffRequired: 6,
    equipmentRequired: 3,
    start: "11:10",
    end: "13:10",
    note: "Long-format tasting zone for student startups.",
  },
  {
    id: "evt-4",
    name: "Poetry Slam",
    category: "Arts",
    cost: 10,
    impact: 29,
    priority: 2,
    staffRequired: 3,
    equipmentRequired: 1,
    start: "13:05",
    end: "14:00",
    note: "Short spoken-word set with quick audience voting.",
  },
  {
    id: "evt-5",
    name: "Startup Sprint",
    category: "Tech",
    cost: 17,
    impact: 48,
    priority: 4,
    staffRequired: 5,
    equipmentRequired: 4,
    start: "13:25",
    end: "15:20",
    note: "Founder-style pitch sprint for rapid concepts.",
  },
  {
    id: "evt-6",
    name: "Stand-up Showcase",
    category: "Comedy",
    cost: 11,
    impact: 25,
    priority: 1,
    staffRequired: 3,
    equipmentRequired: 1,
    start: "15:00",
    end: "16:00",
    note: "Light comedy slot that fills transitions.",
  },
  {
    id: "evt-7",
    name: "Esports Clash",
    category: "Gaming",
    cost: 19,
    impact: 55,
    priority: 4,
    staffRequired: 7,
    equipmentRequired: 5,
    start: "16:05",
    end: "17:25",
    note: "Tournament final with large student draw.",
  },
  {
    id: "evt-8",
    name: "Indie Band Night",
    category: "Music",
    cost: 31,
    impact: 88,
    priority: 5,
    staffRequired: 9,
    equipmentRequired: 6,
    start: "17:00",
    end: "18:30",
    note: "Flagship concert block with the biggest evening pull.",
  },
  {
    id: "evt-9",
    name: "Dance Crew Finals",
    category: "Performance",
    cost: 27,
    impact: 78,
    priority: 4,
    staffRequired: 8,
    equipmentRequired: 6,
    start: "18:10",
    end: "19:30",
    note: "Final crew battle with premium crowd energy.",
  },
  {
    id: "evt-10",
    name: "Innovation Expo",
    category: "Expo",
    cost: 16,
    impact: 36,
    priority: 3,
    staffRequired: 7,
    equipmentRequired: 4,
    start: "10:30",
    end: "16:30",
    note: "Long-running innovation lane with prototypes on display.",
  },
  {
    id: "evt-11",
    name: "Film Night",
    category: "Cinema",
    cost: 13,
    impact: 27,
    priority: 2,
    staffRequired: 4,
    equipmentRequired: 2,
    start: "19:35",
    end: "21:05",
    note: "Screening slot for a relaxed late-night crowd.",
  },
  {
    id: "evt-12",
    name: "Drone Light Show",
    category: "Showcase",
    cost: 23,
    impact: 74,
    priority: 5,
    staffRequired: 6,
    equipmentRequired: 5,
    start: "20:00",
    end: "21:00",
    note: "Closing spectacle that boosts final attendance spikes.",
  },
];

export function createEventId() {
  return `evt-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

export function normalizeEvent(event) {
  return {
    id: String(event.id || createEventId()),
    name: String(event.name || "").trim(),
    category: String(event.category || "General").trim() || "General",
    cost: clamp(Math.round(Number(event.cost) || 0), 1, 999),
    impact: clamp(Math.round(Number(event.impact) || 0), 1, 999),
    priority: clamp(Math.round(Number(event.priority) || 1), 1, 5),
    staffRequired: clamp(Math.round(Number(event.staffRequired) || 2), 1, 50),
    equipmentRequired: clamp(Math.round(Number(event.equipmentRequired) || 1), 1, 40),
    start: isValidTime(event.start) ? event.start : "09:00",
    end: isValidTime(event.end) ? event.end : "10:00",
    note: String(event.note || "").trim(),
  };
}
